### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by skymandr**
This adds templates for creating issues, which might be helpful.

### CODE REVIEW

**Review by pzaino — COMMENTED** [review]
Same as review on Windows-to-Front repo please

**Comment by skymandr** [comment]
> Same as review on Windows-to-Front repo please

Done. Let me know if you want this applied in any other repo.

**Review by pzaino — APPROVED** [review]
looks good, thanks!

**Comment by pzaino** [comment]
Yes let's use the same issue tracker module for all repositories, thanks!

**Pull request merged**
